version: "3.8"

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  bot:
    image: shaegh-bot
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      - TOKEN=$TOKEN
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./app:/var/lib/json/data

    depends_on:
      - postgres
