version: "3.8"

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "5000M"

  bot:
    image: shaegh-bot
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      - TOKEN=$TOKEN
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "500M"
