version: "3.8"

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/

  bot:
    image: shaegh-bot
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      - TOKEN=$TOKEN
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    # links:
    #   - "postgres:5432"
