version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      - TOKEN=$TOKEN

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
