version: "3.8"

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      - TOKEN=$TOKEN
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_DB=POSTGRES
      - POSTGRES_USER=POSTGRES
      - POSTGRES_HOST=POSTGRES
      - POSTGRES_PORT=5432

    depends_on:
      - db
